import js from '@eslint/js';

export default [
	js.configs.recommended,
	{
		files: ['**/*.js', '**/*.svelte'],
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: 'module',
			globals: {
				console: 'readonly',
				document: 'readonly',
				window: 'readonly',
				fetch: 'readonly',
				Promise: 'readonly',
				setTimeout: 'readonly',
				clearTimeout: 'readonly',
				setInterval: 'readonly',
				clearInterval: 'readonly',
				URL: 'readonly',
				location: 'readonly',
				localStorage: 'readonly',
				sessionStorage: 'readonly',
				XMLHttpRequest: 'readonly',
				alert: 'readonly',
				confirm: 'readonly',
				prompt: 'readonly',
				Element: 'readonly',
				HTMLElement: 'readonly',
				NodeList: 'readonly',
				Event: 'readonly',
				CustomEvent: 'readonly',
				WebSocket: 'readonly',
				EventSource: 'readonly',
				FormData: 'readonly',
				Headers: 'readonly',
				Request: 'readonly',
				Response: 'readonly',
				Blob: 'readonly',
				File: 'readonly',
				FileReader: 'readonly',
				Image: 'readonly',
				Audio: 'readonly',
				Video: 'readonly',
				Canvas: 'readonly',
				CanvasRenderingContext2D: 'readonly',
				WebGLRenderingContext: 'readonly',
				Worker: 'readonly',
				SharedWorker: 'readonly',
				ServiceWorker: 'readonly',
				Notification: 'readonly',
				navigator: 'readonly',
				performance: 'readonly',
				crypto: 'readonly',
				atob: 'readonly',
				btoa: 'readonly',
				parseInt: 'readonly',
				parseFloat: 'readonly',
				isNaN: 'readonly',
				isFinite: 'readonly',
				decodeURI: 'readonly',
				decodeURIComponent: 'readonly',
				encodeURI: 'readonly',
				encodeURIComponent: 'readonly',
				AbortController: 'readonly'
			}
		},
		rules: {
			'no-unused-vars': 'warn',
			'no-console': 'warn',
			'no-undef': 'error',
			'no-redeclare': 'error',
			'no-unreachable': 'error',
			'no-empty': 'warn',
			'no-extra-semi': 'warn',
			'no-debugger': 'warn'
		}
	}
];
