# .github/workflows/ci.yml

name: 'CI: Validate Code Quality'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: 'Validate Code, Tests, and Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Node.js v20'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Run Linting, Formatting, and Type Checks'
        run: |
          npm run lint
          npm run format:check
          npm run typecheck

      - name: 'Run Automated Tests'
        run: npm test

      - name: 'Verify Production Build'
        run: npm run build